version: '3.8'

services:
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:8.14.3
#        container_name: elasticsearch
        environment:
            - discovery.type=single-node
            - xpack.security.enabled=false
            - xpack.security.http.ssl.enabled=false
            - ES_JAVA_OPTS=-Xms512m -Xmx512m
        ports:
            - "9200:9200"
            - "9300:9300"
        healthcheck:
          test: [ "CMD", "curl", "-f", "http://localhost:9200/_cluster/health" ]
          interval: 10s
          retries: 5
        volumes:
            - es-data:/usr/share/elasticsearch/data

    mongodb:
        image: mongo:6.0
#        container_name: mongodb
        environment:
            - MONGO_INITDB_ROOT_USERNAME=root
            - MONGO_INITDB_ROOT_PASSWORD=root
        ports:
            - "27017:27017"
        volumes:
            - mongo-data:/data/db

    redis:
        image: redis:6.2
        ports:
            - "6379:6379"

    init-script:
      image: busybox
      depends_on:
        elasticsearch:
          condition: service_healthy
      entrypoint: [ "/bin/sh", "-c", "./init-index.sh" ]
      volumes:
        - ./init-index.sh:/init-index.sh

volumes:
    es-data:
        driver: local
    mongo-data:
        driver: local
